/** Frases de ejemplo para el asistente (máx. 50 para UI y bundle liviano). */
export const ASSISTANT_EXAMPLES: string[] = [
  'Departamento 3 ambientes en venta, Belgrano',
  'Casa en alquiler Palermo hasta 500k',
  'Monocambiente con balcón, CABA',
  'Ph con patio, 2 dormitorios',
  'Oficina en alquiler Microcentro, 40 a 60 m²',
  'Terreno en venta zona norte, acceso a ruta',
  'Duplex 4 ambientes con cochera, Nuñez',
  'Depto 2 dormitorios luminoso, Caballito',
  'Casa quinta con pileta, hasta 200 mil USD',
  'Local comercial en alquiler, avenida con vidriera',
  'Alquiler temporario 2 ambientes Recoleta',
  'Semipiso en venta Las Cañitas, amenities',
  'Monoambiente amoblado para estudiantes, Once',
  'Casa en barrio cerrado Pilar, 3 dormitorios',
  'Departamento con sum y pileta, Puerto Madero',
  'PH sin expensas, Boedo, patio',
  'Cochera fija cubierta en venta, Belgrano',
  'Oficina planta libre, Catalinas',
  'Casa en venta San Isidro, jardín y parrilla',
  'Depto tipo loft, San Telmo, techos altos',
  'Alquiler comercial Galerías Pacífico zona',
  'Casa dos plantas Vicente López, cochera doble',
  'Departamento frente al río, Olivos',
  'Monoambiente divisible, Congreso',
  'Casa en venta Mendoza capital, 4 dormitorios',
  'Depto 3 amb con dependencia, Colegiales',
  'Chalet en country Ezeiza, seguridad 24 hs',
  'Local a la calle, Córdoba capital centro',
  'Alquiler depto 2 amb con mascotas permitidas',
  'Oficina equipada coworking, Palermo Soho',
  'Comprar depto 2 dorm Rosario hasta 120k USD',
  'Departamento bajo expensas, Flores',
  'Piso alto con vista al río, Puerto Norte',
  'Galpón en alquiler, zona industrial Lomas',
  'Depto a estrenar 2 dorm, Villa Urquiza',
  'Casa chorizo reciclada, Almagro',
  'Monoambiente con amenities, Belgrano C',
  'Duplex con terraza propia, Villa del Parque',
  'Oficina categoría A, microcentro CABA',
  'Terreno esquina para desarrollo, Zona Oeste',
  'Casa quinta fin de semana, Escobar',
  'Departamento 4 ambientes con balcón corrido',
  'Alquiler ph planta baja, sin escaleras',
  'Depto luminoso contrafrente silencioso',
  'Casa en venta Mar del Plata, 3 cuadras del mar',
  'Local gastronómico listo para entrar',
  'Cochera moto y baulera, barrio Norte',
  'Semipiso premium cochera fija, Recoleta',
  'Casa en venta Córdoba, barrio Jardín',
  'Departamento con escritorio, home office, Saavedra',
];
